# Generated by Django 3.2.4 on 2021-06-17 14:22

import aaps.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('village_name', models.TextField()),
                ('full_name_english', models.TextField()),
                ('full_name_gujarati', models.TextField()),
                ('is_main_member', models.BooleanField()),
                ('age', models.IntegerField()),
                ('relation_main_member', models.TextField()),
                ('marital_status', enumfields.fields.EnumField(enum=aaps.models.MaritalStatus, max_length=10)),
                ('education', models.TextField()),
                ('business_Occupation', models.TextField()),
                ('father_name_village', models.TextField()),
                ('address', models.TextField()),
                ('mobile_numbers', models.TextField()),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('modified_by', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id', 'village_name', 'created_at', 'updated_at', 'created_by', 'modified_by'],
            },
        ),
    ]
